version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "terraform"
    directory: "/modules/gke"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "terraform"
    directory: "/modules/gitlab"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "terraform"
    directory: "/modules/networking"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "terraform"
    directory: "/modules/monitoring"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
